name: Start Ngrok with Updated Version

on:
  workflow_dispatch:

jobs:
  serve:
    runs-on: windows-latest

    steps:
      - name: Download latest ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.ngrok.com/ngrok/ngrok.exe -OutFile ngrok.exe

      - name: Run Local HTTP Server
        run: |
          python -m http.server 8080 &
          Start-Sleep -Seconds 5

      - name: Start ngrok
        run: |
          .\ngrok.exe config add-authtoken $env:NGROK_AUTH_TOKEN
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "http 8080" -NoNewWindow
          Start-Sleep -Seconds 10

      - name: Get ngrok public URL
        run: |
          $response = Invoke-WebRequest http://127.0.0.1:4040/api/tunnels
          $publicUrl = ($response.Content | ConvertFrom-Json).tunnels[0].public_url
          Write-Output "Ngrok URL: $publicUrl"
