name: Start Dev Server via Ngrok

on:
  workflow_dispatch:  # اجرای دستی

jobs:
  serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python HTTP Server
        run: |
          sudo apt update
          sudo apt install python3 -y

      - name: Start Local Server
        run: |
          nohup python3 -m http.server 8080 &

      - name: Download Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok

      - name: Start Ngrok Tunnel
        run: |
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ./ngrok http 8080 > ngrok.log &
          sleep 10
          curl http://127.0.0.1:4040/api/tunnels

      - name: Show Public URL
        run: |
          curl http://127.0.0.1:4040/api/tunnels | grep -o 'https://[0-9a-z]*\.ngrok.io'
