name: Start Ngrok Server (Windows)

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: windows-latest

    steps:
      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .
          Rename-Item .\ngrok.exe .\ngrok_windows.exe

      - name: Start Local Server (Python)
        run: |
          python -m http.server 8080 &
          Start-Sleep -Seconds 5

      - name: Run ngrok
        run: |
          .\ngrok_windows.exe authtoken $env:NGROK_AUTH_TOKEN
          Start-Process -FilePath ".\ngrok_windows.exe" -ArgumentList "http 8080" -NoNewWindow
          Start-Sleep -Seconds 10

      - name: Get public URL
        run: |
          $response = Invoke-WebRequest http://127.0.0.1:4040/api/tunnels
          $publicUrl = ($response.Content | ConvertFrom-Json).tunnels[0].public_url
          Write-Output "Ngrok URL: $publicUrl"
